.TH man 1 "18 February 2023" "3.0" "The Burning Bush man page"
.SH NAME
.B The Burning Bush
- A simple UNIX command interpreter.

.SH SYNOPSIS
.B bush
[command] [command_string]

.SH COPYRIGHT
.B The Burning Bush
is Copyright (C) 2023 by Ian Duncan and licensed under the MIT license.

.SH DESCRIPTION
.B The Burning Bush
is  an  sh-compatible  command language interpreter that executes
commands read from the standard input.


The Burning Bush is a simplified iteration of a command line interpreter, similar to
.B bash or
.B zsh.

.SH RESERVED WORDS
.B exit:
quits the program, exits the shell.


.B env:
prints the environment variables


.B history:
displays shell history of commands, stored in a file named
.I .burning_bush_history
in the
.I $HOME
directory.


.B help:
print help messages


.B cd:
change shell working directory


.B export:
export attribute for shell variables.


.B echo:
write to the standard output

.B version:
Prints the shell version.

.B echo:
Prints the shell License.


.SH SHELL BUILTIN COMMANDS
The commands

.B exit

.B env

.B help

.B env

.B cd

.B export

.B echo

.B version

.B license

are handled internally.

.SH SEE ALSO
.I sh(1)
,
.I bash(1)

.SH BUGS
Please visit
.B https://github.com/dr8co/bush
for more info.

.SH AUTHOR
Ian Duncan
