name: tests

on:
  push:
    branches: [ "main", "stable" ]
    
  pull_request:
    branches: [ "main", "stable" ]

defaults:
  run:
    shell: bash
    working-directory: ./

jobs:
  ubuntu_clang:
    name: Ubuntu with clang
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Clang
        run: command -v clang || (sudo apt-get update && sudo apt-get install clang-14)
      
      - name: Checkout Repository
        uses: actions/checkout@v3
    
      - name: Install bush
        run: sudo ./install.sh
    
      - name: Test installation
        run: bush help
        
      - name: Test man page installation
        run: man burning-bush
    
      - name: Uninstallation
        run: sudo ./uninstall.sh
      
  ubuntu_gcc:
    name: Ubuntu with gcc
    runs-on: ubuntu-latest
    
    steps:
      - name: Install gcc
        run: command -v gcc || (sudo apt-get update && sudo apt-get install gcc-11)
      
      - name: Checkout Repository
        uses: actions/checkout@v3
    
      - name: Install bush
        run: sudo ./install.sh
    
      - name: Test installation
        run: bush help
        
      - name: Test man page installation
        run: man burning-bush
    
      - name: Uninstallation
        run: sudo ./uninstall.sh
      
  mac_clang:
    name: macOS with clang
    runs-on: macos-latest
    
    steps:
      - name: Install Clang
        run: command -v clang || (brew update && brew install llvm)
      
      - name: Checkout Repository
        uses: actions/checkout@v3
    
      - name: Install bush
        run: sudo ./install.sh
    
      - name: Test installation
        run: bush help
      
      - name: Test man page installation
        run: man burning-bush
    
      - name: Uninstallation
        run: sudo ./uninstall.sh
      
  macos_gcc:
    name: macOS with gcc
    runs-on: macos-latest
    
    steps:
      - name: Install gcc
        run: command -v gcc || (brew update && brew install gcc@11)
      
      - name: Checkout Repository
        uses: actions/checkout@v3
    
      - name: Install bush
        run: sudo ./install.sh
    
      - name: Test installation
        run: bush help
      
      - name: Test man page installation
        run: man burning-bush
    
      - name: Uninstallation
        run: sudo ./uninstall.sh
